// <auto-generated />
using Finanzauto.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Finanzauto.Infrastructure.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240531181216_addDataTableCity")]
    partial class addDataTableCity
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Finanzauto.Domain.Entities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Medellín"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Bogotá"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Ciudad de México"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Buenos Aires"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Lima"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
